<html>
<head>
    <title>Делаем Пиццу</title>
</head>
<body>
<form action="index.php" method="POST">
    <select name="Pizza">
        <?php
        foreach ($pizza as $pizzaName): ?>
            <option value="<?php echo $pizzaName;?>"><?php echo $pizzaName; ?></option>
        <?php endforeach; ?>
    </select>
    <label>
        <input type="checkbox" checked name="dobavki[Соус]"><?php echo $dobavki[0] ?></label>
    <label>
        <input type="number" name="dobavki[Соус]" style="width: 40px;" value="1">Количество</label>
    <input type="submit" value="Расчитать">
</form>






</body>
</html>
